---
- name: "Delete ssh key in PAM - {{ delete_key_username }}"
  delegate_to: localhost
  cyberarkfrlab.pam.delete_account:
    identified_by: "address,username,platform_id"
    username: "{{ delete_key_username }}"
    address: "{{ delete_key_address }}"
    safe: "{{ delete_key_safe_name }}"
    platform_id: "{{ delete_key_platform_id }}"
    secret_type: "key"
    cyberark_session: "{{ cyberark_session }}"
  retries: 3
  delay: 5
