---
- name: Cleanup
  hosts: all
  tasks:
    - name: "Cleanup - Login to PAM Web portal"
      ansible.builtin.include_role:
        name: cyberarkfrlab.pam.login
      vars:
        login_username: "{{ pam_user }}"
        login_password: "{{ pam_pass }}"
        login_identity_url: "{{ identity_url }}"
        login_pam_url: "{{ pam_url }}"

    - name: "Cleanup - Remove created passwords"
      cyberarkfrlab.pam.delete_account:
        identified_by: "address,username,platform_id"
        username: "{{ account.username }}"
        address: "{{ account.address }}"
        safe: "{{ safe_name }}"
        platform_id: "{{ account.platform_id }}"
        secret_type: "{{ account.secret_type }}"
        cyberark_session: "{{ cyberark_session }}"
      loop: "{{ accounts | selectattr('state', 'eq', 'present') }}"
      loop_control:
        loop_var: "account"

    - name: "Cleanup - Logout from PAM Web portal"
      ansible.builtin.include_role:
        name: cyberarkfrlab.pam.logout
