---
- name: Converge
  hosts: all
  tasks:
    - name: "Converge - Login to PAM Web portal"
      ansible.builtin.include_role:
        name: cyberarkfrlab.pam.login
      vars:
        login_username: "{{ pam_user }}"
        login_password: "{{ pam_pass }}"
        login_identity_url: "{{ identity_url }}"
        login_pam_url: "{{ pam_url }}"

    - name: "Converge - Delete account"
      cyberarkfrlab.pam.delete_account:
        identified_by: "address,username,platform_id"
        username: "{{ account.username }}"
        address: "{{ account.address }}"
        secret_type: "{{ account.secret_type }}"
        safe: "{{ safe_name }}"
        platform_id: "{{ account.platform_id }}"
        cyberark_session: "{{ cyberark_session }}"
      retries: 5
      delay: 10
      loop: "{{ accounts }}"
      loop_control:
        loop_var: "account"

    - name: "Converge - Delete 'multiple' accounts"
      cyberarkfrlab.pam.delete_account:
        identified_by: "address,username"
        username: "{{ accounts_multiple_name_prefix }}"
        address: "{{ accounts_multiple_address | default(ansible_default_ipv4.address) }}"
        safe: "{{ safe_name }}"
        cyberark_session: "{{ cyberark_session }}"
        multiple: true
      retries: 5
      delay: 10

    - name: "Converge - Logout from PAM Web portal"
      ansible.builtin.include_role:
        name: cyberarkfrlab.pam.logout
