---
- name: "Delete password from PAM - {{ delete_password_username }}"
  delegate_to: localhost
  cyberarkfrlab.pam.delete_account:
    identified_by: "address,username,platform_id"
    username: "{{ delete_password_username }}"
    address: "{{ delete_password_address }}"
    safe: "{{ delete_password_safe_name }}"
    platform_id: "{{ delete_password_platform_id }}"
    secret_type: "password"
    cyberark_session: "{{ cyberark_session }}"
  register: password_deleted

- name: "Delete password on host - {{ delete_password_username }}"
  when: password_deleted.changed # noqa: no-handler
  ansible.builtin.user:
    name: "{{ delete_password_username }}"
    password: "!"
