---
- name: "Delete password from PAM - {{ delete_password_username }}"
  delegate_to: localhost
  cyberark.pas.cyberark_account:
    identified_by: "address,username,platform_id"
    username: "{{ delete_password_username }}"
    address: "{{ delete_password_address }}"
    safe: "{{ delete_password_safe_name }}"
    platform_id: "{{ delete_password_platform_id }}"
    secret_type: "password"
    state: absent
    cyberark_session: "{{ cyberark_session }}"
  retries: 5
  delay: 10
