---
dependency:
  name: galaxy
  options:
    requirements-file: collections.yml

driver:
  name: default
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        pam_user: ${TEST_PAM_USER}
        pam_pass: ${TEST_PAM_PASS}
        pam_url: ${TEST_PAM_URL}
        identity_url: ${TEST_IDENTITY_URL}

platforms:
  - name: molecule_localhost

scenario:
  test_sequence:
    - dependency
    - syntax
    - converge
    - idempotence
    - verify
