---
- name: Logout from PAM Web portal
  cyberark.pas.cyberark_authentication:
    state: absent
    cyberark_session: "{{ cyberark_session }}"
  when: identity_url is not defined and cyberark_session is defined

- name: "Remove Cyberark session token from Ansible"
  ansible.builtin.set_fact:
    cyberark_session: ""
