---
- name: Cleanup
  hosts: all
  tasks:
    - name: "Cleanup - Login to PAM Web portal"
      ansible.builtin.include_role:
        name: cyberarkfrlab.pam.login
      vars:
        login_username: "{{ pam_user }}"
        login_password: "{{ pam_pass }}"
        login_identity_url: "{{ identity_url }}"
        login_pam_url: "{{ pam_url }}"

    - name: "Cleanup - Delete test safe"
      cyberarkfrlab.pam.delete_safe:
        name: "{{ safe_name }}"
        cyberark_session: "{{ cyberark_session }}"

    - name: "Cleanup - Logout from PAM Web portal"
      ansible.builtin.include_role:
        name: cyberarkfrlab.pam.logout